version: "3.7"
services:

  jupyter-lab:
    container_name: jupyter-lab
    build:
      dockerfile: ./jupyter-lab/Dockerfile
      context: .
    restart: always
    volumes:
      - notebooks:/home/jovyan/notebooks
    networks:
      - traefik
    ports:
      - "8888:8888"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jupyter.rule=Host(`jupyter.vm.mb.marstad.cz`)"

  db-server:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_USER: student
      MYSQL_PASSWORD: student
      MYSQL_DATABASE: 4iz562
    volumes:
      - mysql-data:/var/lib/mysql/
    networks:
      - traefik
    ports:
      - "3306:3306"

volumes:
  mysql-data:
  notebooks:

networks:
  traefik:
    external: true